export enum BasketActionTypes {
  ADD_ARTICLE = "ADD_ARTICLE",
  RESET_ARTICLES = "RESET_ARTICLES",
  SET_QUANTITY_TO_ARTICLE = "SET_QUANTITY_TO_ARTICLE",
  ADD_ONE_QUANTITY_TO_ARTICLE = "ADD_ONE_QUANTITY_TO_ARTICLE",
  REMOVE_ONE_QUANTITY_TO_ARTICLE = "REMOVE_ONE_QUANTITY_TO_ARTICLE",
}
