export enum InventoryMutationTypes {
  RESET_INVENTORY = "RESET_INVENTORY",
  SET_INVENTORIES = "SET_INVENTORIES",
  ADD_INVENTORY = "ADD_INVENTORY",
  UPDATE_INVENTORY = "UPDATE_INVENTORY",
  REMOVE_INVENTORY = "REMOVE_INVENTORY"
}
