type Category {
  id: String
  name: String
  parent: Category
  children: [Category]
  furnitureVersions: [FurnitureVersion]
  attributs: [Attribut]
  organization: Organization
}

type Query {
  categories: [Category]
}

type Mutation {
  deleteCategory(id: String): Boolean
  createCategory(name: String, parentId: String): Category
  updateCategory(id: String, name: String): Category
}
