type Inventory {
  id: String
  name: String
  organization: Organization
  user: User
  address: Address
  placement: Placement
  tags: [Tag]
  items: [Item]
  created_at: String
}

enum Inventory_Type {
  ALL
  ME
  ADDRESS
  PLACEMENT
}

type Query {
  inventories(type: String): [Inventory]
  inventoriesCount(type: Inventory_Type): Int
  inventory(id: String): Inventory
}

type Mutation {
  deleteInventory(id: String): Boolean
  createInventory(name: String): Inventory
  updateInventory(id: String, name: String): Inventory
}
