enum ITEM_STATUS {
  WANTED
  DECLINED
  VALIDATED
}

type Item {
  id: String
  status: ITEM_STATUS
  order: Order
  inventory: Inventory
  furnitureVersion: FurnitureVersion
  variations: [Variation]
}

type Mutation {
  addItemInOrder(furnitureId: String!, orderId: String!): Item
  addItemInInventory(furnitureId: String!, inventoryId: String!): Item
}
