enum ITEM_STATUS {
  WANTED
  DECLINED
  VALIDED
}

type Item {
  id: String
  status: ITEM_STATUS
  order: Order
  inventory: Inventory
  furnitureVersion: FurnitureVersion
  variations: [Variation]
}
