type Order {
  id: String
  name: String
  status: String
  items: [Item]
  countItems: Int
  organization: Organization
  creator: User
  address: Address
  placement: Placement
}

type Query {
  orders(skip: Int, take: Int, status: String): [Order]
  ordersCount(status: String): Int
  order(id: String): Order
}
