type Order {
  id: String
  name: String
  status: String
  items: [Item]
  countItems: Int
  organization: Organization
  creator: User
  address: Address
  placement: Placement
  created_at: String
}

input ItemAddOrder {
  furnitureVersionId: String
  quantity: Int
}

type Query {
  orders(skip: Int, take: Int, status: String): [Order]
  ordersCount(status: String): Int
  order(id: String): Order
}

type Mutation {
  addOrder(name: String, items: [ItemAddOrder]): Order
}
