type Tag {
  id: String
  name: String
  organization: Organization
}

type Query {
  tags: [Tag]
}

type Mutation {
  deleteTag(id: String): Boolean
  createTag(name: String): Tag
  updateTag(id: String, name: String): Tag
}
