type User {
  id: String
  email: String
  firstname: String
  lastname: String
  phone: String
  role: String
  status: String
  organization: Organization
  orders: [Order]
  furnitureVersions: [FurnitureVersion]
  inventories: [Inventory]
  address: Address
  placement: Placement
}

type AuthPayload {
  token: String
  user: User
  organization: Organization
}

type Me {
  user: User
  organization: Organization
}

type Query {
  users: [User]
}

type Mutation {
  signup(email: String!, password: String!, organization: String!): AuthPayload
  login(email: String!, password: String!): AuthPayload
  me: Me
}
