export enum FurnitureMutationTypes {
  SET_FURNITURES_WITH_LATEST_FURNITURE_VERSION = "SET_FURNITURES_WITH_LATEST_FURNITURE_VERSION",
  ADD_FURNITURE_WITH_LATEST_FURNITURE_VERSION = "ADD_FURNITURE_WITH_LATEST_FURNITURE_VERSION"
}
