export enum AttributActionTypes {
  RESET_ATTRIBUT = "RESET_ATTRIBUT",
  SET_ATTRIBUTS = "SET_ATTRIBUTS",
  ADD_ATTRIBUT = "ADD_ATTRIBUT",
  UPDATE_ATTRIBUT = "UPDATE_ATTRIBUT",
  REMOVE_ATTRIBUT = "REMOVE_ATTRIBUT"
}
