export enum OrganizationMutationTypes {
  SET_ORGANIZATION = "SET_ORGANIZATION",
  ADD_USER_IN_ORGANIZATION = "ADD_USER_IN_ORGANIZATION",
  SET_USERS_IN_ORGANIZATION = "SET_USERS_IN_ORGANIZATION",
  UPDATE_USER_IN_ORGANIZATION = "UPDATE_USER_IN_ORGANIZATION",
  DELETE_USER_IN_ORGANIZATION = "DELETE_USER_IN_ORGANIZATION",
}
