export enum CategoryActionTypes {
  RESET_CATEGORY = "RESET_CATEGORY",
  ADD_CATEGORY = "ADD_CATEGORY",
  SET_CATEGORIES = "SET_CATEGORIES",
  REMOVE_CATEGORY = "REMOVE_CATEGORY",
  UPDATE_CATEGORY = "UPDATE_CATEGORY",
  SET_CATEGORIES_TREE = "SET_CATEGORIES_TREE",
}
